function hdr = SeaBASS_metadata_headers(cruiseid,ecotaxa_file)
%% FUNCTION HDR = SEABASS_METADATA_HEADERS(CRUISEID,ECOTAXA_FILE)
% Description:
%   Define metadata used in SeaBASS Metadata Headers
%   No spaces are allowed in metadata headers!
%
% Input:
%   cruiseid     | char containing unique cruise id (required)
%   ecotaxa_file | char containing name of ecotaxa file exported (optional)
% 
% Output:
%   hdr          | structure containing requred metadata information
%
% References:
%   https://seabass.gsfc.nasa.gov/wiki/metadataheaders
%
% Author:
%   Brita Irving <bkirving@alaska.edu>
par_file = 1; % 1(default) = set headers based on par file, 0 = set headers based on zoo file
if nargin == 0
  fprintf('Error in script: hdr = SeaBASS_metadata_headers(cruiseid)\n')
  error('  ! Expected cruiseid !')
elseif nargin == 1
  % default to empty character
  ecotaxa_file = '';
else
  if contains(ecotaxa_file,'PAR')
    par_file = 1;
  else
    par_file = 0;
  end
end
%% Define hdr
hdr = struct();
hdr.investigators = ''; % The contributor of the data file. Principal investigator is listed first, followed by any associate investigators/analysts.
hdr.affiliations  = ''; % A list of affiliations (e.g. university, laboratory) for each investigator. Multiple affiliations may be listed comma separated (no spaces). Their ordering should match the ordering of the investigators.
hdr.contact       = ''; % An email address for at least one of the investigators or point of contact for the data file. Multiple email addresses may be listed comma separated (no spaces).
hdr.experiment    = ''; % The name of the over-arching, long-term research project or funding program. Experiment names are used to generate a dataset-specific DOI and, generally, will contain multiple cruises or deployments and encompass data spanning multiple months or years
hdr.cruise        = ''; % The name of the specific cruise (or subset of the experiment) where the data in the file were collected. Do not exceed a meximum length of 25 characters. Please be consistent and use a consensus-selected name if data from the same cruise are being submitted by multiple different investigators.
hdr.station       = ''; % The name of the station or deployment where data in the file were obtained. If the data file contains measurements from multiple stations, use the value NA and include station as a column in your data matrix. NA may also be used if the data were not assigned station names.
hdr.calfiles      = ''; % /calibration_files
hdr.caldates      = ''; % /calibration_date
hdr.data_type     = '';
hdr.data_status   = ''; % preliminary, update, or final
hdr.missing       = ''; % 
hdr.delimiter     = ''; % The "comma" delimiter is used to separate data values in the above example. Either comma, space, or tab is a valid choice, however, the default recommendation is comma.
hdr.inst_mfr      = ''; % /instrument_manufacturer
hdr.inst_model    = ''; % /instrument_model
hdr.comments      = ''; % Can be anything, as long as prefixed with !
switch cruiseid
  %% ------------------------------------------------------------------
  case 'SR1812' % EXPORTSNP 2018 Sally Ride (Survey cruise)
    hdr.investigators = 'Andrew_M_P_McDonnell';
    hdr.affiliations  = 'University_of_Alaska_Fairbanks';
    hdr.contact       = 'amcdonnell@alaska.edu';
    hdr.experiment    = 'EXPORTS';
    hdr.cruise        = 'EXPORTSNP';
    hdr.station       = 'NA';
    hdr.calfiles      = 'uvp_calibration_report_of_uvp5sn207a_from_uvp5sn002_20180129';
    hdr.caldates      = '20180129';
    hdr.data_type     = 'cast';
    hdr.missing       = '-9999'; 
    hdr.delimiter     = 'comma';
    hdr.inst_mfr      = 'Hydroptic'; % /instrument_manufacturer
    hdr.inst_model    = 'UVP5hd'; % /instrument_model
    switch par_file
      case 1 % PAR file
        hdr.data_status   = 'final';
        hdr.documents = {'UVP_Particle_and_Zooplankton_Characterization_Protocol.pdf'...
          'Write_SEABASS_UVP_par.m'};
        hdr.comments = {...
          '! COMMENTS';...
          '!';...
          '! Underwater Vision Profiler 5 High Definition Unit Serial Number 207 manufactured by Hydroptic';...
          '! This data was exported from the main UVP database Ecotaxa (https://ecotaxa.obs-vlfr.fr)';...
          ['! Ecotaxa export source file: ' ecotaxa_file];...
          '! Ecotaxa Particle Module project identifier: sn207_2018_exports_np_sr1812_filtered';...
          ['! R/V Cruise Id = ' cruiseid];...
          '! Contributors: ';...
          '!  UVP operator: Jessica Pretty, University of Alaska Fairbanks';...
          '!  Data preparation: Brita Irving, University of Alaska Fairbanks';...
          '!';...
          '! depth represents the center of 5 meter depth bins';...
          '! This data is inclusive of all types of particles and plankton'};
      case 0 % ZOO file
        hdr.data_status   = 'preliminary';
        hdr.documents     = {'UVP_Particle_and_Zooplankton_Characterization_Protocol_20210114.pdf'...
          'Write_SEABASS_UVP_zoo.m'...
          'WoRMS_AphiaID_taxa_match.m'...
          'Ecotaxa_Image_Key_EXPORTS_SR1812.pdf'}; %
        hdr.comments      = {...
          '! COMMENTS';...
          '!';...
          '! Underwater Vision Profiler 5 High Definition Unit Serial Number 207 manufactured by Hydroptic';...
          '! This data was exported from the main UVP database Ecotaxa (https://ecotaxa.obs-vlfr.fr)';...
          ['! Ecotaxa export source file: ' ecotaxa_file];...
          '! Ecotaxa Particle Module project identifier: sn207_2018_exports_np_sr1812_filtered';...
          '! Ecotaxa project page: https://ecotaxa.obs-vlfr.fr/prj/1591';...
          ['! R/V Cruise Id = ' cruiseid];...
          '!';...
          '! Contributors: ';...
          '!  UVP operator: Jessica Pretty, University of Alaska Fairbanks';...
          '!  Image validation: Rachel Lekanoff, Jessica Pretty, Tristan Biard, Stephanie O’Daly';...
          '!  Data preparation: Brita Irving, University of Alaska Fairbanks';...
          '!';...
          '! depth represents the center of 5 meter depth bins';...
          '! t008 definition: rectangular/tabular fecal pellets, possibly from salps'};
      otherwise
        error('par_file not set as expected\n');
    end % PAR or ZOO file 

  %% ------------------------------------------------------------------
  case 'RR1813' % EXPORTSNP 2018 Roger Revelle (Process cruise)
    hdr.investigators = 'Nils_Haentjens,Emmanuel_Boss,Lee_Karp-Boss';
    hdr.affiliations  = 'University_of_Maine';
    hdr.contact       = 'nils.haentjens@maine.edu,emmanuel.boss@maine.edu,lee.karp-boss@maine.edu';
    hdr.experiment    = 'EXPORTS';
    hdr.cruise        = 'EXPORTSNP';
    hdr.station       = 'NA';
    hdr.calfiles      = 'TBD';%'uvp_calibration_report_of_uvp5sn201a_from_uvp5sn002_20180122_rep_20200325';
    hdr.caldates      = '20180129';
    hdr.data_type     = 'cast';
    hdr.missing       = '-9999'; 
    hdr.delimiter     = 'comma';
    hdr.inst_mfr      = 'Hydroptic'; % /instrument_manufacturer
    hdr.inst_model    = 'UVP5hd'; % /instrument_model
    switch par_file
      case 1 % PAR file
        hdr.data_status   = 'final';
        hdr.documents = {'UVP_Particle_and_Zooplankton_Characterization_Protocol.pdf'...
          'Write_SEABASS_UVP_par.m'};
        hdr.comments = {...
          '! COMMENTS';...
          '!';...
          '! Underwater Vision Profiler 5 High Definition Unit Serial Number 201 manufactured by Hydroptic';...
          '! This data was exported from the main UVP database Ecotaxa (https://ecotaxa.obs-vlfr.fr)';...
          ['! Ecotaxa export source file: ' ecotaxa_file];...
          '! Ecotaxa Particle Module project identifier: uvp5_sn201_exports01_filtered';...
          ['! R/V Cruise Id = ' cruiseid];...
          '! Contributors: ';...
          '!  UVP operator: Emmanuel Boss';...
          '!  Data preparation: Brita Irving, University of Alaska Fairbanks';...
          '!';...
          '! depth represents the center of 5 meter depth bins';...
          '! This data is inclusive of all types of particles and plankton'};
      case 0 % ZOO file
        hdr.data_status = 'preliminary';
        hdr.documents   = {'UVP_Particle_and_Zooplankton_Characterization_Protocol_20210114.pdf'...
          'Write_SEABASS_UVP_zoo.m'...
          'WoRMS_AphiaID_taxa_match.m'...
          'Ecotaxa_Image_Key_EXPORTS_SR1812.pdf'}; %
        hdr.comments      = {...
          '! COMMENTS';...
          '!';...
          '! Underwater Vision Profiler 5 High Definition Unit Serial Number 201 manufactured by Hydroptic';...
          '! This data was exported from the main UVP database Ecotaxa (https://ecotaxa.obs-vlfr.fr)';...
          ['! Ecotaxa export source file: ' ecotaxa_file];...
          '! Ecotaxa Particle Module project identifier: uvp5_sn201_exports01_filtered';...
          '! Ecotaxa project page: https://ecotaxa.obs-vlfr.fr/prj/1286';...
          ['! R/V Cruise Id = ' cruiseid];...
          '! Contributors: ';...
          '!  UVP operator & Image validation: Emmanuel Boss';...
          '!  Data preparation: Brita Irving, University of Alaska Fairbanks';...
          '!';...
          '! depth represents the center of 5 meter depth bins';...
          '! t008 definition: rectangular/tabular fecal pellets, possibly from salps'};
      otherwise
        error('par_file not set as expected\n');
    end % PAR or ZOO file 
  %% ------------------------------------------------------------------
  otherwise % CRUISE ID
    fprintf('SeaBASS Metadata Headers not defined for cruiseid: %s\n',cruiseid)
    error('Must define SeaBASS metadata headers here ... follow examples above')
end
end %% FUNCTION HDR = SEABASS_METADATA_HEADERS(CRUISEID,ECOTAXA_FILE)
